--START TABLE DESIGN (PARTITIONED)
CREATE TABLE TRANSACTIONS (
	ID BIGSERIAL PRIMARY KEY,
	ACCOUNT_ID BIGINT NOT NULL,
	AMOUNT NUMERIC(12, 2) NOT NULL,
	TYPE VARCHAR(10) CHECK (TYPE IN ('credit', 'debit')),
	DESCRIPTION TEXT,
	CREATED_AT TIMESTAMP NOT NULL
)
PARTITION BY
	RANGE (CREATED_AT);
--END TABLE DESIGN (PARTITIONED)


-- Start Monthly Partitions
CREATE TABLE TRANSACTIONS_2026_05 PARTITION OF TRANSACTIONS FOR
VALUES
FROM
	('2026-05-01') TO ('2026-06-01');
-- End Monthly Partitions

-- Start Indexes (CRITICAL for 10K RPS)
CREATE INDEX idx_account_date 
ON transactions (account_id, created_at DESC);

CREATE INDEX idx_account_type 
ON transactions (account_id, type);
-- End Indexes (CRITICAL for 10K RPS)